=== sivrad/matrix/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/sivrad/matrix/main/schema.json",
    "title": "Type",
    "description": "Represent a Type.",
    "definitions": {
        "field": {
            "title": "Field",
            "description": "Field of a Type.",
            "type": "object",
            "properties": {
                "type": {
                    "title": "Type",
                    "type": "string",
                    "description": "Type of the field."
                },
                "label": {
                    "title": "Label",
                    "type": "string",
                    "description": "Label of the field."
                },
                "description": {
                    "title": "Description",
                    "type": "string",
                    "description": "Description of the field.",
                    "pattern": "[A-Z].+\\.{1}$"
                },
                "flags": {
                    "type": "array",
                    "description": "Flags for the field.",
                    "items": {
                        "type": "string",
                        "enum": ["readonly"]
                    }
                },
                "defaultValue": {
                    "type": [
                        "number",
                        "string",
                        "boolean",
                        "object",
                        "array",
                        "null"
                    ],
                    "description": "The default value if not given"
                }
            },
            "additionalProperties": false,
            "required": ["type"]
        }
    },
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "Schema URL.",
            "pattern": "^https:\\/\\/raw\\.githubusercontent\\.com\\/sivrad\\/matrix-schema\\/main\\/type\\.json$"
        },
        "name": {
            "type": "string",
            "description": "The name of the schema."
        },
        "label": {
            "type": "string",
            "description": "The label of the schema."
        },
        "description": {
            "type": "string",
            "description": "The description of the schema.",
            "pattern": "[A-Z].+\\.{1}$"
        },
        "icon": {
            "type": "string",
            "description": "The type icon."
        },
        "parent": {
            "type": ["string", "null"],
            "description": "The parent ID of the schema."
        },
        "flags": {
            "type": "array",
            "description": "Flags for the type.",
            "items": {
                "type": "string",
                "enum": ["abstract", "readonly", "no-instances"]
            }
        },
        "fields": {
            "type": "object",
            "description": "The fields for the schema.",
            "additionalProperties": {
                "$ref": "#/definitions/field"
            }
        },
        "fieldValues": {
            "type": "object",
            "description": "Values for parent fields.",
            "additionalProperties": {
                "type": ["string", "number", "array", "object"]
            }
        }
    },
    "additionalProperties": false,
    "required": ["name", "label", "description", "icon"]
}

=== sivrad/matrix/types/std/Person.json
{
    "$schema": "https://raw.githubusercontent.com/sivrad/matrix-schema/main/type.json",
    "name": "Person",
    "label": "Person",
    "description": "A person is a being that has certain capacities or attributes such as reason, morality, consciousness or self-consciousness, and being a part of a culturally established form of social relations such as kinship, ownership of property, or legal responsibility.",
    "icon": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Person_icon_BLACK-01.svg/1200px-Person_icon_BLACK-01.svg.png",
    "parent": "Organism",
    "fields": {
        "surname": {
            "label": "Surname",
            "type": "string | null",
            "description": "The surname of the person.",
            "defaultValue": null
        },
        "middleName": {
            "label": "Middle Name",
            "type": "string | null",
            "description": "The middle name of the person.",
            "defaultValue": null
        },
        "givenName": {
            "label": "Given Name",
            "type": "string | null",
            "description": "The given name of the person.",
            "defaultValue": null
        }
    },
    "fieldValues": {
        "species": "human"
    }
}

=== sivrad/matrix/types/std/Entity.json
{
    "$schema": "https://raw.githubusercontent.com/sivrad/matrix-schema/main/type.json",
    "name": "Entity",
    "label": "Entity",
    "description": "An entity is a physical thing that can or has existed.",
    "icon": "https://static.thenounproject.com/png/6887-200.png",
    "fields": {
        "end": {
            "label": "End",
            "type": "Time",
            "description": "A time when the thing stopped existing."
        },
        "height": {
            "label": "Height",
            "type": "quantity.Length",
            "description": "The height of the entity."
        },
        "mass": {
            "label": "Mass",
            "type": "quantity.Mass",
            "description": "The mass of the entity."
        }
    }
}

=== sivrad/matrix/types/quantity/Mass.json
{
    "$schema": "../../schema.json",
    "name": "Mass",
    "label": "Mass",
    "description": "Mass is a measure of the amount of matter in an object.",
    "icon": "https://img.icons8.com/ios/452/weight.png",
    "parent": "Scalar",
    "fields": {
        "kilograms": {
            "label": "Kilograms",
            "type": "number",
            "description": "The mass in kilograms."
        }
    }
}

=== sivrad/matrix/types/quantity/Time.json
{
    "$schema": "https://raw.githubusercontent.com/sivrad/matrix-schema/main/type.json",
    "name": "Time",
    "label": "Time",
    "description": "A quantity of time.",
    "icon": "https://img.icons8.com/pastel-glyph/2x/clock--v2.png",
    "parent": "Scalar",
    "fields": {
        "seconds": {
            "label": "Seconds",
            "type": "number",
            "description": "The number of seconds."
        }
    }
}

=== sivrad/matrix/types/quantity/Duration.json
{
    "$schema": "../../schema.json",
    "name": "Duration",
    "label": "Duration",
    "description": "A duration of time.",
    "icon": "https://img.icons8.com/pastel-glyph/2x/clock--v2.png",
    "parent": "Scalar",
    "fields": {
        "seconds": {
            "label": "Seconds",
            "type": "number",
            "description": "The number of seconds."
        }
    }
}

=== sivrad/matrix/types/std/Organism.json
{
    "$schema": "../../schema.json",
    "name": "Organism",
    "label": "Organism",
    "description": "An individual animal, plant, or single-celled life form.",
    "icon": "https://icon-library.com/images/cells-icon/cells-icon-26.jpg",
    "parent": "Entity",
    "fields": {
        "species": {
            "label": "Species",
            "type": "string",
            "description": "The species of the organism.",
            "defaultValue": null
        }
    }
}

=== sivrad/matrix/types/std/Organization.json
{
    "$schema": "../../schema.json",
    "name": "Organization",
    "label": "Organization",
    "description": "An organization is an entity – such as a company, an institution, or an association – comprising one or more people and having a particular purpose.",
    "icon": "https://freeiconshop.com/wp-content/uploads/edd/many-people-outline.png",
    "parent": "Thing",
    "fields": {
        "name": {
            "type": "string",
            "label": "Name",
            "description": "The organization name."
        }
    }
}

=== sivrad/matrix/types/quantity/Length.json
{
    "$schema": "https://raw.githubusercontent.com/sivrad/matrix-schema/main/type.json",
    "name": "Length",
    "label": "Length",
    "description": "Length is a measure of distance.",
    "icon": "https://static.thenounproject.com/png/1693-200.png",
    "parent": "Scalar",
    "fields": {
        "meters": {
            "label": "Meters",
            "type": "number",
            "description": "The length in meters."
        }
    }
}
